# Generated by Django 5.1.2 on 2024-11-29 15:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cart_farmer_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=models.SET(core.models.deleted_user), to='core.farmer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='buyer',
            field=models.ForeignKey(on_delete=models.SET(core.models.deleted_user), to='core.buyer'),
        ),
    ]
